# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jayden Kang
tagline:          'Jayden Kang'
description:      'My portfolio containing my work regarding GIS, ecology, and photography. Made by <a href="https://instagram.com/jeidun" target="_blank">@jeidun</a>.'
url:              https://jeidun.github.io
baseurl:          https://jeidun.github.io/poole/

author:
  name:           'Jayden Kang'
  url:            https://instagram.com/jeidun

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jeidun/jeidun.github.io.git

# Theme

theme: jekyll-theme-quartz
plugins:
  - jekyll-remote-theme
